### ISSUE TITLE
Create a job in Travis to run test whitout need create a pull request

### ISSUE THREAD

**Issue by nestornav** [pumascript/puma#94]

**Comment by Undre4m** [comment]
_Needs Info._ Travis runs CI procedure whenever a commit is pushed to the repo, or a forked project elevates a PR for merging.
>**Important note**
CI **only runs** on the main repo as it's so configured. **NOT** on forked projects as they need individual configuration as far as i'm aware.

Since CI seems to work as intended i'll close this issue until further information is provided.
